### PR TITLE
Focus appearance encompass

### PR DESCRIPTION
**Pull request by mbgower**
In progress changes to Understanding document (and some normative text)

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wcag/pull/2283.html" title="Last updated on Mar 25, 2022, 10:50 PM UTC (db4d168)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wcag/2283/edd4b65...db4d168.html" title="Last updated on Mar 25, 2022, 10:50 PM UTC (db4d168)">Diff</a>

### CODE REVIEW

**Comment by mbgower** [comment]
@alastc this is in progress. please do not merge yet, but I wanted you to have a chance to see what I'm doing. more updates to come

**Review by bruce-usab — APPROVED** [review]
Thank you!

**Review by bruce-usab — APPROVED** [review]
These changes all look good to me.  Thank you very much.

**Review by bruce-usab — APPROVED** [review]
I am comfortable using (and defining) encloses (as opposed to encompasses).  Thanks!

**Comment by alastc** [comment]
At this point it will be easier to remove things from this than revert, so I'll merge this and the base branch into main.

**Pull request merged**
