### PR TITLE
Focus-Appearance rework

### PR DESCRIPTION
**Pull request by alastc**
Based on the recent meetings.

[Preview the SC text and revised understanding doc](https://raw.githack.com/w3c/wcag/focus-appearance-rework/understanding/22/focus-appearance-minimum.html).

To do: The updates to the AAA version.

Closes: #2219, #2222, #2226,

***

### :boom: Error: 500 Internal Server Error :boom: ###

[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Apr 27, 2022, 9:01 PM UTC)_.

<details>
<summary>More</summary>

PR Preview relies on a number of web services to run. There seems to be an issue with the following one:

:rotating_light: [Spec Generator](https://www.w3.org/2015/labs/) - Spec Generator is the web service used to build specs that rely on ReSpec.

:link: [Related URL](https://labs.w3.org/spec-generator/?type=respec&url=https%3A%2F%2Fraw.githubusercontent.com%2Fw3c%2Fwcag%2F7e26284b38d50723d7ba5b84fe4db043634e860d%2Fguidelines%2Findex.html%3FisPreview%3Dtrue)

```

😭  Sorry, there was an error generating the HTML. Please report this issue!
Specification: http://labs.w3.org/spec-generator/uploads/bnr0Mh?isPreview=true&publishDate=2022-04-27
ReSpec version: 32.1.4
File a bug: https://github.com/w3c/respec/
Error: Error: Evaluation failed: Timeout: document.respec.ready didn't resolve in 29140ms.
    at ExecutionContext._evaluateInternal (/u/spec-generator/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext.evaluate (/u/spec-generator/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:16)
    at async generateHTML (/u/spec-generator/node_modules/respec/tools/respecDocWriter.js:221:12)
    at async toHTML (/u/spec-generator/node_modules/respec/tools/respecDocWriter.js:92:18)
    at async Object.generate [as respec] (file:///u/spec-generator/generators/respec.js:15:44)
    at async file:///u/spec-generator/server.js:244:48

```

_If you don't have enough information above to solve the error by yourself (or to understand to which web service the error is related to, if any), please [file an issue](https://github.com/tobie/pr-preview/issues/new?title=Error%20not%20surfaced%20properly&body=See%20w3c/wcag%232281.)._
</details>

### CODE REVIEW

**Comment by bruce-usab** [comment]
@alastc &mdash; Please see [my comment in the Google doc](https://docs.google.com/document/d/1TI_DsJjfg9RW_A9C1XfqgtfYqNMfnxeCz6lxjpOQ9rk/edit?disco=AAAAXBDHDx8).  I believe a rigid reading of <q>continuous</q> for the encompasses definition to be problematic.  I don't have a good suggestion, except to drop that adjective from the definition (which then leaves the possibility of a dashed border with too much empty space).

**Comment by alastc** [comment]
>  I believe a rigid reading of continuous for the encompasses definition to be problematic. 

Hi @bruce-usab, remember that the exception is still based on area, so any non-continuous indicators would fall through to the exception.

**Comment by bruce-usab** [comment]
@alastc &mdash; I wrote something similar in the Google doc.
> any non-continuous indicators would fall through to the exception

I do not agree that this is good enough, because the exception is part of the SC, not the definition.

On the survey, I asked:  Does a UI like [marching ants](https://en.wikipedia.org/wiki/Marching_ants) meets the definition for encompasses (and I am of the strong opinion that it should)?

I was scribe, so I did not track your reply on the call.  You said <q>**Yes**, because of the exception.</q>  That was enough for me at the time.

With the benefit of hindsight, I wish your answer had been more along the line:  <q>**No**, but it is okay, because of the exception.</q>  That might have clued me in more (at the time of the call) to note that I think it is a significant problem to use <q>encompasses</q> with such a particular caveat, which puts our use of the term outside the mainstream understanding of the word.

My suggestion is to _move_ the <q>continuous</q> qualifier from the definition to the text of the SC.

**Comment by bruce-usab** [comment]
Thanks @alastc.&nbsp; I am more comfortable with a specialize particular meaning for <q>surrounds<.q> than <q>encompasses</q> &mdash; not that I can give a good defense as to why.  I think it might be better _not_ to have a defined term in this case, but I very much prefer what you have here:  <q>surrounds</q> in the SC, and <q>encompasses</q> as part of the definition of the defined term.

**Comment by mbgower** [comment]
@bruce-usab My concern with using “surrounds” is that it fails to address some common outliers, such as a button that changes its color. By making the definition for “encompass” include “surrounds” as well as some related but distinct terms, we manage to tackle all those edge cases while maintaining a word that has a broader meaning than “surrounds” while including it. Hope that helps

**Comment by alastc** [comment]
@mbgower That changing colour technique wouldn't pass the primary part of the SC anyway, that would fall through to the exception (and pass). 

Bruce's point is just about which term matches the intent best, and I'm fairly ambivalent about that (I thought they both did, but others have said that 'encompasses' wasn't quite right).

**Comment by mbgower** [comment]
Why wouldn't it pass the primary?
If you have a grey button that contrasts 3:1 with a white background, and you make it black, the pixels of the focus indicator contrast against themselves, and the black contrasts against the white background. Since the change "includes the whole of the" button, it meets the primary.

**Comment by mbgower** [comment]
I assume using "embiggen" is a joke? Otherwise, I'm not sure why you would propose replacing what you call a "fancy word" with a term i've never heard of which, when I looked it up, seems to have been first used on a Simpson's episode.

**Comment by mbgower** [comment]
If the problem here is that you're trying to make it clear a dashed line fails, might I suggest:
"solidly bounds, surrounds or includes the whole of"

**Comment by mbgower** [comment]
"Continuously encompass" just seems awkward to me. 
There may not be a way of wording this elegantly. Do we have to resort to "surrounds the visual presentation of the user interface component with an unbroken line"? I find that overly prescriptive, personally.

 For my money "solidly bounds, surrounds or includes the whole of" as a definition of encompasses is pretty good.

**Comment by bruce-usab** [comment]
@mbgower &mdash; "solidly bounds, surrounds or includes the whole of" is fine as a concept.  It is _not_ fine as definition for "encompasses" because a minority of people using that word would assume "solidly".  The fact that we dare not leave encompasses undefined illustrates why there is a problem.

This is where I believe we are with the top half of the SC:

When a user interface components has keyboard focus, the focus indicator:
- Encompasses the visual presentation of the user interface component;
- Has a contrast ratio of at least 3:1 between its pixels in the focused and unfocused states;
- Has a contrast ratio of at least 3:1 against adjacent colors.

So how about instead:

When a user interface components has keyboard focus, the focus indicator:
- Solidly bounds, surrounds or includes the whole of the visual presentation of the user interface component;
- Has a contrast ratio of at least 3:1 between its pixels in the focused and unfocused states;
- Has a contrast ratio of at least 3:1 against adjacent colors.

**Comment by mbgower** [comment]
See both https://github.com/w3c/wcag/pull/2283 and https://github.com/w3c/wcag/pull/2284 for variations on this

**Review by bruce-usab — CHANGES_REQUESTED** [review]
With this PR, I am still seeing <q>encompasses</q> as a defined term with <q>solidly</q> as a required characteristics.  That detail goes above and beyond usual meaning of the wordr.

But I am also seeing definitions for focus and perimeter which I am comfortable with.  So I am not confident that I looking at the most recent version.

**Comment by mbgower** [comment]
@bruce-usab most up to date of my proposed changes are in 2284 (linked in my last comment). Note that they are cumulative, so it helps to look at 2283 first to see the progression from 2281

**Pull request merged**
