### PR TITLE
Change `<ol>` to `<ul>` when no order is intended (non-normative)

### PR DESCRIPTION
**Pull request by patrickhlauke**
The understanding documents are oddly inconsistent when it comes to use of `<ol>` and `<ul>`. This edits all cases (particularly in the newer 2.2 understanding docs, but some older ones too) where a list does not have an explicit order and should just be an unordered list

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wcag/pull/3518.html" title="Last updated on Mar 23, 2024, 3:47 PM UTC (44277aa)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wcag/3518/bf44269...44277aa.html" title="Last updated on Mar 23, 2024, 3:47 PM UTC (44277aa)">Diff</a>

### CODE REVIEW

**Comment by bruce-usab** [comment]
Briefly discuss on call 3/22/2024, and we determined needed closer review.

@patrickhlauke might this be expedited by spitting the non-normative documents into their own PR?

Also, it is sometimes helpful to have LI numbered if only because that makes them easier to reference in a conversation.  Is that enough justification to assert that order matters?

**Comment by patrickhlauke** [comment]
I guess I could split this PR into two for the changes in the `guidelines` folder (normative) and the ones in the `conformance-challenges` and `understanding` (informative)

I admit I don't buy the rationale about numbered list items as reference, at least not in the cases that I patch here.

**Comment by patrickhlauke** [comment]
@bruce-usab I've removed the changes to normative documents (I'm assuming `conformance-challenges` is non-normative?) which would make this less controversial. Filing the same change to the normative ones as a separate PR

**Comment by patrickhlauke** [comment]
Done https://github.com/w3c/wcag/pull/3756

**Review by bruce-usab — COMMENTED** [review]
Thank you @patrickhlauke for splitting off the normative docs.  I had hoped to get to this PR on the call today, but I messed up the opportunity for that.

Everything looks good to me, but I think the conformance-challenges file has hard-coded references to 2.1 instead of 2.2.  I think that might be addressed in a different PR in the future, or maybe split off the one file to get the other 13 quickly through?

I retract my comment about maybe OL having some utility.
- Some of the LI are sorted by SC numbering, so OL is unhelpful.
- Other places OL is clearly semantically correct, since there is not any apparent order.  I can't think of situations where having a number to refer to would matter.  The lists are short and it's better to refer to the thing than the number for the thing.

**Comment by fstrr** [comment]
@patrickhlauke There's a couple of merge conflicts that have appeared. The Conformance Challenges one is straight forward, but the Text Spacing one looks like there's more to it than that and is conflicting with #3572, [which was merged into main three days ago](https://github.com/w3c/wcag/blob/main/understanding/21/text-spacing.html). Could you take a look at that one please?

**Comment by patrickhlauke** [comment]
@fstrr thanks for checking. sigh...

**Comment by fstrr** [comment]
@patrickhlauke [Could be worse](https://github.com/w3c/wcag/pull/3757)…

**Comment by patrickhlauke** [comment]
@fstrr sorted (the text spacing one was odd ... it was showing a huge chunk being out of sync, but in reality it wasn't)

**Comment by fstrr** [comment]
@patrickhlauke Oh, that's good.

**Comment by patrickhlauke** [comment]
@fstrr want me to have a look at the mega-conflicts in the other one? I suspect it's something small, like a space before a closing `/`, but in lots of files, and in a way that confuses github's merge capability...

**Review by fstrr — APPROVED** [review]

**Comment by fstrr** [comment]
@patrickhlauke If you want to, that would be super helpful. It looks like your "chore: update HTML files for xslt/xml processing" update is the issue with the 66 files, so, yeah, it's probably something really straightforward. Thanks :)

**Review by bruce-usab — APPROVED** [review]
I have reviewed changes since I last reviewed, and I have on concerns.

**Comment by alastc** [comment]
@patrickhlauke to check that, once built, the techniques still come out (e.g. for focus-not-obscured-min). 

The XSLT may forget to output them if it's not expecting `<ul>`s.

**Comment by bruce-usab** [comment]
This PR includes the [https://github.com/w3c/wcag/blob/main/conformance-challenges/index.html](one source file) for Challenges with Accessibility Guidelines Conformance and Testing, and Approaches for Mitigating Them](https://w3c.github.io/wcag/conformance-challenges/).  I think that is fine, since (1) it is an AG WG document, which (2) is a working draft, and (3) this is editorial.  Per the discussion on the call 4/12, @mbgower this detail might be worth flagging when sent for WG review.

**Pull request merged**
