### PR TITLE
Add actionable advice to "Large scale (text) > Note 1" in the glossary

### PR DESCRIPTION
**Pull request by patrickhlauke**
Closes https://github.com/w3c/wcag/issues/228

### CODE REVIEW

**Comment by joshueoconnor** [comment]
This looks editorial (and makes sense to me) but is it?

**Comment by awkawk** [comment]
This should be discussed for 2.1.  There's no point in making this change in the 2.0 document.  As to whether it is editorial, I don't think that adding actionable advice can be editorial.  We will need to route this for group review, although it may be easy.

**Comment by patrickhlauke** [comment]
Yes, this was intended for 2.1 (I've given up on trying to make any changes to 2.0 ;) ). And agree it's not editorial since it gives actual advice/suggestion

**Comment by awkawk** [comment]
closing with the WCAG 2.1 label on it for future reference.

**Pull request closed without merging**
