### PR TITLE
Change `touch target` to just `target`

### PR DESCRIPTION
**Pull request by patrickhlauke**
It's incorrect to just talk about `touch target`, since thee relevant SCs apply to pointers in general (i.e. also mouse, stylus).

As this changes the definition, I guess it's classed as a substantive change rather than an editorial one?

### CODE REVIEW

**Review by scha14 — APPROVED** [review]

**Review by scha14 — APPROVED** [review]

**Comment by patrickhlauke** [comment]
Ping @alastc

**Comment by patrickhlauke** [comment]
Any news on this @alastc ?

**Comment by patrickhlauke** [comment]
resolved the merge conflict that crept in since this was first submitted in 2020. any chance this could be considered soon @alastc ?

**Comment by patrickhlauke** [comment]
would be nice to see this in the upcoming 2.2 without then having to go once again through some lengthy "this is a normative term change" update later on... @alastc

**Comment by awkawk** [comment]
This seems like a bona-fide errata - not sure how the "touch" was incorporated into the note.

**Pull request merged**
