### PR TITLE
WCAG22 - Focus Visible enh updates

### PR DESCRIPTION
**Pull request by alastc**
Previews of:
- [Focus appearance (minimum) understanding](https://raw.githack.com/w3c/wcag/wcag22-focus-visible-enh-updates/understanding/22/focus-appearance-minimum.html)
- [Focus appearance (enhanced) understanding](https://raw.githack.com/w3c/wcag/wcag22-focus-visible-enh-updates/understanding/22/focus-appearance-enhanced.html)

Updates to resolve:
#1004, #1075, #1038, #1053, #1055, #1064, #1067, #1075, #1115, #301

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wcag/pull/1121.html" title="Last updated on Aug 4, 2020, 8:31 PM UTC (6866f0c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wcag/1121/e4dfc4d...6866f0c.html" title="Last updated on Aug 4, 2020, 8:31 PM UTC (6866f0c)">Diff</a>

### CODE REVIEW

**Comment by detlevhfischer** [comment]
@alastc The changelog still seems to have a link title "Focus Visible Enhanced" (but with correct fragment identifier)

**Comment by alastc** [comment]
Hi Detlev,

I think we'll leave that there, as it was called that, but then add another entry for the updated name.
However, it did remind me that I should add the (enhanced) version to the 'updates' section at the top, thanks :-)

**Comment by mraccess77** [comment]
I have 2 questions:
* For adjacent contrast - does this require contrast for both sides of the focus rectangle or just one side?   I believe SC 1.4.11 allows for one side.
* Can we overlook intermediate colors like a gray shadow that might be between the focus indicator and the adjacent colors as the eye skips over those (as discussed in SC 1.4.11 understanding document).

**Comment by alastc** [comment]
Hi Jon,

The 3rd bullet is (currently) against "all adjacent colors", so both sides. Remembering the test-cases, if it doesn't contrast in either direction it does need to be thicker. Also, if you move the outline in or out slightly, both sides would be against one colour (barring gradients etc).

We allow for areas of less contrast for the 1st two bullets, so long as they fulfill the overall area & contrast change. 
For the 3rd bullet I'd treat it like testing text-contrast, where you pick the least contrasting bit. 

I'm not sure which bit of 1.4.11 you mean, is it "Gestalt principles such as the "law of continuity" can be used to ignore minor overlaps with other graphical objects or colors." That was in the context of (usually) larger graphical objects where your eye is following a shape. For a focus indicator it is more about tracking that appearance/disappearance, I would be inclinced to keep it strict.

**Comment by mraccess77** [comment]
Thanks @alastc My comment about skipping certain colours comes from this statement in the understanding document of SC 1.4.11
"If components use several colors, any color which does not interfere with identifying the component can be ignored for the purpose of measuring contrast ratio. For example, a 3D drop-shadow on an input, or a dark border line between contrasting backgrounds is considered to be subsumed into the color closest in brightness (perceived luminance)."

**Comment by ajanec01** [comment]
This is the part I was also thinking about. Correct me if I'm wrong, currently, I interpret 1.4.11 and 2.4.11 as if they were complimenting each other because of the idea of the subsumed colours.

 **focus appearance:**
- focus indicator must have the minimum indication area
- the colour changes for the indicator must have sufficient contrast between the focused and unfocused state
-either all adjacent colours for the indicator have sufficient contrast ratio (page background and the UI component) or the indicator is at least 2 css px thick.

The third bullet does not cater for a 2px thick indicator which meets the first two bullet points requirement to have enough contrast ratio against the page background. However, 1.4.11 does. As far as I understand 1.4.11 says that the focus indicator must have enough contrast ratio against the page background but not the UI component itself. This is based on the part of the understanding page which @mraccess77 quoted and the part in the "Relationship with Use of Color and Focus Visible" section which says:

"... the visual focus indicator for a component must have sufficient contrast against the adjacent background when the component is focused,..."

The question is, have I interpreted 1.4.11 correctly. If yes, then they fit nicely with each other. If not, then there's an issue where the bullet point no 3 and 1.4.11 can be mutually exclusive.

**Comment by patrickhlauke** [comment]
GitHub warns me (when going through https://github.com/w3c/wcag/branches/stale) that this PR can't/shouldn't be deleted because another open PR refers to this branch. leaving this intact for now.

**Pull request merged**
