### PR TITLE
Wcag22 focus appearance size update

### PR DESCRIPTION
**Pull request by alastc**
Based on survey and discussion: https://www.w3.org/2021/01/19-ag-minutes.html#t02

### CODE REVIEW

**Comment by detlevhfischer** [comment]
I take it that this example would meet the requirement?
http://3needs.org/en/testing/code/focus-visibility.html#bordertest
Would it still meet the requirement if the focus was also vertically offset?

**Comment by JAWS-test** [comment]
> Would it still meet the requirement if the focus was also vertically offset?

I had already addressed this problem: https://github.com/w3c/wcag/pull/936#issuecomment-552729350. Unfortunately without success

**Comment by alastc** [comment]
Hi @detlevhfischer,

So, looking at the buttons with `border-bottom: solid 2px #A9A9A9`, (changing from `#595959`) with a white adjacent background with an internal background of black, and they are around 52 x 33px, so with focus area of 2*52 = 104.

I don't think that meets the min size requirement, which would be either: 
- (52 * 2) + (33 * 2) -4 = 166
- 33*4 = 132

The bottom border changes from `#595959` to `#a9a9a9` which doesn't quite meet the change of contrast (2.98:1), although that's a minor tweak.

It would meet the adjacent contrast bullet.

But the main thing is that the size isn't sufficient.

**Comment by detlevhfischer** [comment]
hi @alastc 
Could it be that in your answer, you are addressing the (dated, and marked as dated) example above the one I linked to? What I was getting at (the example below "Purposefully horrid example...") is that the lack of any requirement regarding the proximity of the focus to the element focused (here, a 4px border offset by 100px) might be a problem.

**Pull request merged**
