### PR TITLE
Removing Flash Techniques

### LINKED ISSUE #1140: It is time to remove the Flash techniques
The technology is at End of Life (https://www.adobe.com/products/flashplayer/end-of-life.html) - let's just remove the techniques.

### PR DESCRIPTION
**Pull request by awkawk**
Closes #1140

### CODE REVIEW

**Comment by patrickhlauke** [comment]
@awkawk changed the first comment/thread starter here to then trigger github auto-closing of the related issue when this is merged (assuming this is the one PR that will fully close that)

**Comment by awkawk** [comment]
I think that I got all of the references to Flash techniques. We need to also:
* remove techniques/flash directory entirely.
* remove working-examples/flash-* files
* Update WCAG QRG references

**Comment by alastc** [comment]
I'm tagging with 'ready for survey', but is there a particular rational for this in terms of timing?

Don't get me wrong, I was in favor pre-2.1, but I'm wondering if there is a trigger to be aware of?

**Comment by awkawk** [comment]
@alastc no, no particular timing except I was reminded of the EOL announcement and had a long call that I could poke at the repo to find the places to remove references.

I switched to a new machine and don't have the GitHub app installed and configured yet, so the deletion of directories and multiple files is a problem for me until I do, so if you can delete those for this PR it will make it more ready for survey.

**Comment by michael-n-cooper** [comment]
I'd like to review this before merge.

**Comment by alastc** [comment]
I've removed the technique files and working examples, but I'm inclined to leave the wcag20 references, unless there's somewhere it will show up?

**Comment by michael-n-cooper** [comment]
> I've removed the technique files and working examples, but I'm inclined to leave the wcag20 references, unless there's somewhere it will show up?

I'm not sure what you mean by wcag20 references, are these references from wcag20 to flash techniques, or the other way around, or something else?

**Comment by alastc** [comment]
I just meant there are still references from the XML files to the flash techniques, but as we won't be updating WCAG 2.0 that seems fine.

If you're happy with it, the group approved so I'll merge.

**Pull request merged**
