### PR TITLE
Tweak section headings understanding wording

### LINKED ISSUE #2035: Understanding doc for section headings uses two different meanings of section
This paragraph uses section both to encompass any division of a page/publication and also as a level below a "subtopic":

> The intent of this Success Criterion is to provide headings for sections of a Web page, when the page is organized into sections. For instance, long documents are often divided into a variety of chapters, chapters have subtopics and subtopics are divided into various sections, sections into paragraphs, etc. When such sections exist, they need to have headings that introduce them.

While I can assume the concluding sentence is talking to any division, using the term with different meanings makes it sound like it applies to a level below subtopics as mentioned in the previous sentence.

Could the second use of section as a subdivision be written out of the middle sentence for additional clarity? For example:

> For instance, long documents are often divided into a variety of chapters, chapters have subtopics, etc.

(Paragraphs aren't sections so no need to mention them at all.)

### PR DESCRIPTION
**Pull request by patrickhlauke**
Remove ambiguous use of `sections`.

Closes https://github.com/w3c/wcag/issues/2035

### CODE REVIEW

**Review by bruce-usab — APPROVED** [review]
This is a good catch, thank you.

**Comment by patrickhlauke** [comment]
all thanks go to @mattgarrish for spotting it

**Comment by patrickhlauke** [comment]
Any news on this @alastc ?

**Review by bruce-usab — APPROVED** [review]

**Review by dbjorge — APPROVED** [review]

**Review by alastc — APPROVED** [review]

**Review by ljoakley — APPROVED** [review]
simplifying a run on sentance.

**Pull request merged**
