### PR TITLE
Change 1.4.4 related mentions of "at least 200%" to "up to 200%"

### PR DESCRIPTION
**Pull request by patrickhlauke**
Closes https://github.com/w3c/wcag/issues/2923

### CODE REVIEW

**Review by giacomo-petri — APPROVED** [review]

**Comment by detlevhfischer** [comment]
Hmm - I have my doubt that all readers will parse "up to 200%" correctly. It could be understood as meaning: "resize should have an effect, and you should be able to enlarge text to a maximum value of 200% (but not more)" - implying that resizing to 150% would be sufficient as well. I would just scrap the "up" for clarity.

**Comment by GreggVan** [comment]
I  think "up to"  is perfectly understandable.  I  don't  think anyone in any position of authority to judge would think that something must be "adjustable up to 200%"  would be satisfied by something that stopped at 150%.    And also no such judge would think it should be capped at 200%  unless you said  "up  to a max of 200%" or even "up to a max of 200% and not more".      This is not to say that "all readers" would  say this because it is not possible to say that "all readers" will read anything correctly.  But that should not be our goal.    We should make it as understandable as possible.  So if you have alternate wording that you think would be better -- it is always great to hear it.

**Comment by patrickhlauke** [comment]
> I have my doubt that all readers will parse "up to 200%" correctly.

it's the exact wording used in the normative SC text. not disagreeing, just pointing out that if there's confusion, it already starts with the actual SC itself

**Comment by detlevhfischer** [comment]
@GreggVan I just gave my take as a non-native speaker with a good grasp of English. The guidance is read by all kinds of people (not just native speakers) who implement stuff, often without a deep understanding of accessibility  - so that "position of authority to judge" thing strikes me as odd. Anyway, if others think there is no problem, that's fine. Personally I am more comfortable with "at least 200%".

**Review by bruce-usab — APPROVED** [review]

**Comment by alastc** [comment]
From the meeting: It's in the SC, the understanding document is quite consistent on "up to", so we think the test-procedure should reflect the SC text.

**Pull request merged**
