### PR TITLE
Tweak 1.2.9 understanding to remove reference to "video conferences"

### PR DESCRIPTION
**Pull request by patrickhlauke**
Closes https://github.com/w3c/wcag/issues/1836

### CODE REVIEW

**Comment by patrickhlauke** [comment]
Any news on this @alastc ?

**Comment by patrickhlauke** [comment]
@alastc @mbgower et al. any chance this non-controversial change could be merged at some point?

**Comment by bruce-usab** [comment]
The term "web-based voice conferencing" struck me as odd.  I would rather "web-based audio conferencing" or "web-based telephony".

**Comment by patrickhlauke** [comment]
> The term "web-based voice conferencing" struck me as odd. I would rather "web-based audio conferencing" or "web-based telephony".

not quite sure ... telephony has, I think, more unintended connotations like VoIP and being able to call landlines etc.

**Comment by patrickhlauke** [comment]
yup, happy with the "web-based audio" tweak

**Pull request merged**
