### PR TITLE
Tech icon font img role v3

### PR DESCRIPTION
**Pull request by alastc**
Taking over from the #531 PR.

### CODE REVIEW

**Comment by alastc** [comment]
Hi Jake,

I re-created the branch as the original one (that I created!) was too old. I think I got everything (technique, 1 working example page, font folder).

Do you know where the fonts came from? (I.e. are the licensing issues or a license file for that needed?)

**Comment by jake-abma** [comment]
Hi @alastc I created the fonts myself with https://icomoon.io/

**Comment by jake-abma** [comment]
**What is the license for IcoMoon icons/fonts?**
There is a license link for each icon pack in IcoMoon's library.
If you are using your own vectors, there are no license requirements for using the IcoMoon app.

https://icomoon.io/#faq

**Comment by alastc** [comment]
Ah, so you created it rather than using one with a license, perfect. :-)

**Pull request merged**
