### PR TITLE
Capitalization of WCAG 2.0 Parsing explainer text

### PR DESCRIPTION
**Pull request by fstrr**
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wcag/pull/3958.html" title="Last updated on Aug 29, 2024, 12:00 PM UTC (dc219d3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wcag/3958/f9c7225...dc219d3.html" title="Last updated on Aug 29, 2024, 12:00 PM UTC (dc219d3)">Diff</a>

### CODE REVIEW

**Comment by fstrr** [comment]
Those are some chunky-looking merge conflicts.

I was going to delete this branch and re-do it, but I cannot find the [Parsing content that's on the live WCAG 2.0](https://www.w3.org/WAI/WCAG20/Understanding/parsing.html) in the repo. The [2.0 Understanding Parsing page in this repo](https://github.com/w3c/wcag/blob/main/understanding/20/parsing.html) has different content in it.

**Comment by patrickhlauke** [comment]
> I was going to delete this branch and re-do it, but I cannot find the [Parsing content that's on the live WCAG 2.0](https://www.w3.org/WAI/WCAG20/Understanding/parsing.html) in the repo. The [2.0 Understanding Parsing page in this repo](https://github.com/w3c/wcag/blob/main/understanding/20/parsing.html) has different content in it.

maybe @kfranqueiro or @iadawn may know what's going on here...

**Comment by kfranqueiro** [comment]
The 2nd-to-last commit in this branch exists on the `WCAG-2.1` branch, not on `main`, so that's why there's a ton of commits here when there should only be 1. Even then, though, this branch is many commits out of date from that branch, so I'm a little confused as to how this PR has only been created now for a commit from April 19, 2023?

It may be more advisable to manually re-apply the changes seen in `3b11b13` to a new branch based on `main`, since the content of `parsing.html` has changed considerably due to its removal in WCAG 2.2.

**Comment by fstrr** [comment]
A while ago, @patrickhlauke pointed out that there were over 250 branches on this repo, so I decided to [look and see what they were](https://github.com/w3c/wcag/issues/3878), what could be deleted, and what looked useful but had gone stale for some reason. This is a branch that, for whatever reason, didn't get merged in at the time, so I created a PR for it last night.

I'll try to take a look at this tonight. I'll create a new branch, copy the current live content into it and then apply the edits. I think that's what you're saying to do.

**Comment by kfranqueiro** [comment]
FYI, upon [searcing for an earlier PR for this branch](https://github.com/w3c/wcag/pulls?q=is%3Apr+head%3Acapitalization), there is indeed an open PR against the `WCAG-2.1` branch at #3154.

**Comment by fstrr** [comment]
So, we should take off and nuke the entire branch and PRs from orbit?

**Comment by kfranqueiro** [comment]
I don't think this branch/PR warrants any action against `main`.

At most, we could potentially address the original PR #3154 as it pertains to the `WCAG-2.1` branch, although I'll note that it also has conflicts there in one paragraph.

The `WCAG-2.1` branch hasn't been touched in a long time though, and I'm not sure if it is expected to receive any unique updates? (Just yesterday I began investigating as to whether it's realistic to update 2.1 informative materials directly from `main` using the Eleventy build system.)

**Comment by kfranqueiro** [comment]
@patrickhlauke I'm not sure why a further merge commit was attempted on this PR, but its commit history is very problematic at this point.

As I pointed out previously, #3154 is the version opened against the WCAG-2.1 branch. The original PR changes _one file_ - which does not make sense to change on the main branch, because it's the file for Parsing, which was hollowed out as obsolete on the main branch.

This PR should be closed. If we are interested in merging this into the WCAG-2.1 branch, we should merge #3154 instead - it is based on the same branch, but targeting the correct one. This additional PR was opened against main by mistake.

**Comment by patrickhlauke** [comment]
> @patrickhlauke I'm not sure why a further merge commit was attempted on this PR, but its commit history is very problematic at this point.

ah, my bad, I was having a trawl through hanging PRs and didn't scroll far enough down its history of comments to see we already talked about it.

I'd say let's close it then for now. If there's still outstanding problems, we can tackle them in a fresh PR.

**Pull request closed without merging**
