### PR TITLE
Pointer target spacing update

### PR DESCRIPTION
**Pull request by scha14**
* View [SC pointer target spacing](https://raw.githack.com/w3c/wcag/6c6cc164ebb1452c495dc8b4ec394c78bffd54a8/guidelines/sc/22/pointer-target-spacing.html)
*  View [Understanding pointer target spacing](https://raw.githack.com/w3c/wcag/scha14-pointer-target-spacing/understanding/22/pointer-target-spacing.html)
* [Related issues ](https://github.com/w3c/wcag/labels/2.5.8%20Pointer%20Target%20Spacing)

### CODE REVIEW

**Comment by detlevhfischer** [comment]
Looks good to me.

**Comment by alastc** [comment]
Thanks for creating this, I did a few updates to match the google doc, but if you get a chance to update the figures & captions, that would be great.

**Comment by scha14** [comment]
Figures and captions are updated. @alastc could you please take a look to make sure they render okay?

**Comment by detlevhfischer** [comment]
I tried to create a link for the[ rendered view of understanding pointer target spacing](https://raw.githack.com/w3c/wcag/6c6cc164ebb1452c495dc8b4ec394c78bffd54a8/understanding/22/pointer-target-spacing.html) via githack but I am not sure these are the updated graphics...

**Comment by scha14** [comment]
They are the latest graphics. They are the same images with the dimensions
updated to match the new SC

**Comment by alastc** [comment]
I think Detlev just meant that the middle would should be marked 'pass'?

**Comment by scha14** [comment]
I can do that. Wasn't sure that this didn't qualify as enclosed and was
trying to avoid the case with these tiny buttons at the corners of images.

**Comment by alastc** [comment]
I think the idea on the middle one is that the icon is on the edge, so overlapping but not enclosed by the picture, therefore it has the spacing top and left.

**Comment by scha14** [comment]
It's updated

**Comment by detlevhfischer** [comment]
OK I have also updated the githack link.
@scha14 @alastc I think we still need to update or replace the third example - the pixel figures underneath the buttons make no sense, it is obvious that all buttons are considerably wider than 24 px (and "Push" has got to be wider than 20 px), and the relative dimensions are not correct, either.
Maybe we can think of another example? Or just drop this example?  A pull-down menu example might be relevant... (my head is empty right now...)

**Comment by scha14** [comment]
@detlevhfischer updated the figure so the relative sizes make more sense. We can replace with another figure as well.

**Comment by alastc** [comment]
As the updates weren't approved, I'll merge this into 'main'.

**Pull request merged**
