### PR TITLE
WCAG 2.2 - Dragging SC

### PR DESCRIPTION
**Pull request by alastc**
The new proposed Dragging SC transferred from the [google doc](https://docs.google.com/document/d/1LaVX-RTaLQL0tN4G3NhOTlmj16swt0VzC7ssaAjqIwg/edit#):

- [Understanding document](https://raw.githack.com/w3c/wcag/wcag22-dragging/understanding/22/dragging.html) 
- General technique: [Ensuring that a single pointer operable alternative is available for dragging movements that operate on content](https://raw.githack.com/w3c/wcag/wcag22-dragging/techniques/general/G-Dragging.html)
- Failure technique: [Failure of Success Criterion 2.5.X Dragging due to not providing a single pointer method for the user to operate a function that does not require a dragging movement](https://raw.githack.com/w3c/wcag/wcag22-dragging/techniques/failures/F-dragging.html)

The SC text is embedded in the understanding document for review.

Survey: https://www.w3.org/2002/09/wbs/35422/wcag22-dragging/results
Last minutes: https://www.w3.org/2020/03/24-ag-minutes.html#item02

***

### :boom: Error: 500 Internal Server Error :boom: ###

[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on May 27, 2020, 2:36 PM UTC)_.

<details>
<summary>More</summary>

PR Preview relies on a number of web services to run. There seems to be an issue with the following one:

:rotating_light: [Spec Generator](https://www.w3.org/2015/labs/) - Spec Generator is the web service used to build specs that rely on ReSpec.

:link: [Related URL](https://labs.w3.org/spec-generator/?type=respec&url=https%3A%2F%2Frawcdn.githack.com%2Fw3c%2Fwcag%2Fc0b90293945437549a2dd9c0be3a681dda3be06e%2Fguidelines%2Findex.html%3FisPreview%3Dtrue)

```

😭  Sorry, there was an error generating the HTML. Please report this issue!
[36mSpecification: https://rawcdn.githack.com/w3c/wcag/c0b90293945437549a2dd9c0be3a681dda3be06e/guidelines/index.html?isPreview=true&publishDate=2020-05-27[39m
[36mReSpec version: 25.6.0[39m
[36mFile a bug: https://github.com/w3c/respec/[39m
[36mError: Error: Evaluation failed: Timeout: document.respecIsReady didn't resolve in 16382ms.[39m
[36m    at ExecutionContext._evaluateInternal (/u/spec-generator/node_modules/puppeteer/lib/ExecutionContext.js:122:13)[39m
[36m    at runMicrotasks (<anonymous>)[39m
[36m    at processTicksAndRejections (internal/process/task_queues.js:97:5)[39m
[36m    at async ExecutionContext.evaluate (/u/spec-generator/node_modules/puppeteer/lib/ExecutionContext.js:48:12)[39m
[36m    at async generateHTML (/u/spec-generator/node_modules/respec/tools/respecDocWriter.js:128:12)[39m
[36m    at async fetchAndWrite (/u/spec-generator/node_modules/respec/tools/respecDocWriter.js:95:18)[39m
[36m    at async Object.generate [as respec] (/u/spec-generator/generators/respec.js:14:20)[39m
[36m    at async generate (/u/spec-generator/server.js:91:29)[39m
[36m  -- ASYNC --[39m
[36m    at ExecutionContext.<anonymous> (/u/spec-generator/node_modules/puppeteer/lib/helper.js:111:15)[39m
[36m    at DOMWorld.evaluate (/u/spec-generator/node_modules/puppeteer/lib/DOMWorld.js:112:20)[39m
[36m    at runMicrotasks (<anonymous>)[39m
[36m    at processTicksAndRejections (internal/process/task_queues.js:97:5)[39m
[36m  -- ASYNC --[39m
[36m    at Frame.<anonymous> (/u/spec-generator/node_modules/puppeteer/lib/helper.js:111:15)[39m
[36m    at Page.evaluate (/u/spec-generator/node_modules/puppeteer/lib/Page.js:860:43)[39m
[36m    at Page.<anonymous> (/u/spec-generator/node_modules/puppeteer/lib/helper.js:112:23)[39m
[36m    at generateHTML (/u/spec-generator/node_modules/respec/tools/respecDocWriter.js:128:23)[39m
[36m    at runMicrotasks (<anonymous>)[39m
[36m    at processTicksAndRejections (internal/process/task_queues.js:97:5)[39m
[36m    at async fetchAndWrite (/u/spec-generator/node_modules/respec/tools/respecDocWriter.js:95:18)[39m
[36m    at async Object.generate [as respec] (/u/spec-generator/generators/respec.js:14:20)[39m
[36m    at async generate (/u/spec-generator/server.js:91:29)[39m
[36m[39m
```

_If you don't have enough information above to solve the error by yourself (or to understand to which web service the error is related to, if any), please [file an issue](https://github.com/tobie/pr-preview/issues/new?title=Error%20not%20surfaced%20properly&body=See%20w3c/wcag%231113.)._
</details>

### CODE REVIEW

**Comment by jpascalides** [comment]
This is an important SC but feel that more examples are needed. Of particular concern are slider-based interactions. Would this SC introduce a variety of slider variants that exhibit different implementations to satisfy the SC? If so, the end result could conflict with user expectations, making the interactions more complex for screen reader users. Perhaps we should consider if this is more a UA issue to address at the native control level.

**Comment by alastc** [comment]
Hi @jpascalides,

I'm not sure how this would be UA issue? All the dragging type components I can think of are author-implemented, if there aren't (web) native components for dragging features then I think it has to be on the author.

The folks in MAFT did find some nice implementations, did you see the doc linked at the end of the original google doc? The link is: https://docs.google.com/document/d/13QWLthBoEU6xuJQ4UrYOwuvJp0a42Z70JRjAsjtv1m4/edit#heading=h.uacsmsv3zr96

**Comment by jpascalides** [comment]
Hi @alastc,

Sliders, which natively implement drag and single pointer are in many browsers. Would you consider this an example of of the functionality being embedded in UA?

**Comment by alastc** [comment]
Hi Justine,

If you mean browser-native sliders like this example:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/range

You can already tap on those to select a point on the slider, they don't require a dragging operation. So in a WCAG context, so long as in your accessibility supported UAs do support tapping to select, this requirement would be met.

However, if the author creates a custom version, they would also have to implement a similar (or other) mechanism.

-Alastair

**Comment by arariyo87** [comment]
In mobile, there is sorting when the order of a list (or grid) content using drag and drop action as shown in the example 1 below.

like this example 1:
https://unitid.nl/windowsphonepatterns/uap_pattern/drag-and-drop

This content is not operated by a single pointer only works with drag and drop.
However, the following methods are used to someone who struggle with performing path-based gestures.
1.setting(iOS)
2.Accessibility
3.Touch
4.To Activate "AssistiveTouch"
5.Custom
6.Hold and drag

like this example 2:
https://youtu.be/RNSplpCh_A8

Using the "AssistantTouch", sort a list (or grid) content in example 1 is sufficient Techniques?

**Pull request merged**
