### PR TITLE
Fixed typo on H80

### PR DESCRIPTION
**Pull request by MelSumner**
If merged, this PR would add a missing quotation mark that was causing an example to not render correctly. 

Screenshot of issue: 
Example 3: Newspaper website

### CODE REVIEW

**Review by rscano — APPROVED** [review]

**Comment by rscano** [comment]
Fix refer to https://www.w3.org/WAI/WCAG22/Techniques/html/H80

**Review by patrickhlauke — APPROVED** [review]

**Comment by bruce-usab** [comment]
Discussed on TF call 4/12 and Ready for approval.

**Review by bruce-usab — APPROVED** [review]
Thank you @MelSumner

**Comment by mbgower** [comment]
This was previously resolved by another change, and no longer exists in the code.

**Pull request closed without merging**
