### PR TITLE
Update all reference to the now moved ARIA Practices patterns and examples

### LINKED ISSUE #2457: Star rating example DOCUMENT NOT FOUND 2.4.11: Focus Appearance (Minimum)
Star rating example DOCUMENT NOT FOUND 2.4.11: Focus Appearance (Minimum)
https://w3c.github.io/wcag/understanding/focus-appearance-minimum.html

> [star-rating widget](https://www.w3.org/TR/wai-aria-practices-1.2/examples/slider/slider-rating.html#ex_label)

Maybe this one? (but stable link would be preferred...)
https://w3c.github.io/aria-practices/examples/slider/slider-rating.html

### PR DESCRIPTION
**Pull request by patrickhlauke**
- also renames links to the guide itself (new canonical unversioned name of "ARIA Authoring Practices Guide"
- removes completely outdated links to old sections that don't exist anymore

Closes #2457

### CODE REVIEW

**Comment by patrickhlauke** [comment]
possibly worth backporting to 2.1 and 2.0 as well?

**Comment by patrickhlauke** [comment]
(mutters something about [Cool URIs don't change](https://www.w3.org/Provider/Style/URI) ... )

**Comment by alastc** [comment]
@michael-n-cooper - worth adding for 2.1 as well.

**Comment by WickyNilliams** [comment]
Thanks @patrickhlauke

**Pull request merged**
