### PR TITLE
Tech fitting labels inputs viewport

### PR DESCRIPTION
**Pull request by jake-abma**
New technique for Using Fitting Labels and Inputs for Reflow, you can preview [Using Fitting Labels and Inputs for Reflow](https://rawgit.com/w3c/wcag/tech-fitting-labels-inputs-viewport/techniques/css/tech-fitting-labels-inputs-reflow.html ), and there is an associated [example page](https://rawgit.com/w3c/wcag/tech-fitting-labels-inputs-viewport/working-examples/css-fitting-inputs/index.html).

### CODE REVIEW

**Comment by jake-abma** [comment]
- paragraph starting "Layouts..." changed
- Removed: "Medium complex"

**Comment by jake-abma** [comment]
https://github.com/w3c/wcag/pull/510 related

**Comment by alastc** [comment]
Hi Jake,

Now that we have the working-examples folder setup ok, you can create examples in the same branch. I think it stops a lot of the faffing...

**Comment by alastc** [comment]
Hi Jake, other branch merged into this (remaining open) and a few little wording updates applied.

**Comment by alastc** [comment]
Just noting for @allanj-uaag, @rachaelbradley and @lauracarlson that the example has been combined into this PR, so comments from #510 apply here.

I think the comments have been addressed, but worth checking.

**Comment by alastc** [comment]
@michael-n-cooper I think it's ready. I did a test build, updated the file names, and updated the understanding document. Please merge if it's ok, comment if there's anything I missed.

**Pull request merged**
