### PR TITLE
Removing mdash to get build working

### PR DESCRIPTION
**Pull request by alastc**

### CODE REVIEW

**Review by bruce-usab — COMMENTED** [review]
I am happy to have noticed this, since I am one of those pendants who chooses carefully between hyphen, en dash, em dash, and minus sign.  I have made a mental note to let that go for AG WG docs.  :-)

**Comment by alastc** [comment]
I think it's fine if an actual mdash it put in, but the automatic-build chokes on `&mdash;`. I just don't know how to type an mdash in VS code...

**Comment by awkawk** [comment]
`&#8212;` is an m-dash
`&#8211;` is an n-dash

**Comment by bruce-usab** [comment]
If you want to _type_ an en dash or em dash:
* Windows:  alt-numpad-0150 , alt-numpad-0151  (that is, hold down alt, type four digits from number pad keyboard only, let up alt key &mdash; even harder on laptop keyboard)
* Mac OS X:  option-hyphen , option-shift-hyphen

**Pull request merged**
