### PR TITLE
Consistency: "Resize text" > "Resize Text"

### PR DESCRIPTION
**Pull request by patrickhlauke**
all other SC titles use title case (with some oddities), except for this one

### CODE REVIEW

**Comment by patrickhlauke** [comment]
Any news on this @alastc ?

**Comment by awkawk** [comment]
This should just be an editorial errata

**Comment by patrickhlauke** [comment]
my thoughts as well, @awkawk ...

**Comment by awkawk** [comment]
@patrickhlauke even editorial errata need WG approval. But this should be a simple survey question that will get unanimous agreement and a quick CFC.

**Pull request merged**
