### PR TITLE
Target Size addition of user agent and equivalent exceptions

### PR DESCRIPTION
**Pull request by mbgower**
This incorporates what I believe was the group decision on incorporating legal into the Essential bullet.
As well I have added exceptions for user agent and equivalent, which are drawn from the wording that exists in the Target Size (Enhanced) SC, as discussed in https://github.com/w3c/wcag/issues/1976

Addresses #1976, #1904.

### CODE REVIEW

**Comment by mbgower** [comment]
@alastc Time permitting, we can possibly discuss this on tomorrow's call? I will try to get the Dragging understanding document updated before that meeting as well.

**Comment by mraccess77** [comment]
Thanks for making these updates.  The exception for alternatives is "The function can be achieved through a different control that has an area of at least 24 by 24 CSS pixels" but the SC itself allows for further exceptions such as no other targets in a 24x24 area.   Was this on purpose to make the alternative exception stricter than the SC itself?  I'm fine with that - I just wanted to confirm the intent.

**Comment by patrickhlauke** [comment]
logically, it should really be that the different control satisfies the SC (including its exception), rather than just a more limited aspect of it, in my opinion.

**Comment by detlevhfischer** [comment]
Agree that it might be more straightforward to say 
> **Equivalent:** The function can be achieved through a different control that meets the requiremens of this SC 

...or similar - but since this exception does not spell out that the equivalent control has to be on the same page, it could technically lead to a recursive "passing fo the bucket" even across several pages (the control has an equivalent which itself does not meet the SC but has an equivalent elsewhere etc.) - so this exception appears to be diluting the requirement too much. How can a formulation prevent this?

**Comment by patrickhlauke** [comment]
i'd rather have the risk of recursion (which I would say is low, because you'd then essentially "short-circuit" the passing the buck as long as there's one control at the end of the chain that passes the SC, and THAT is then the alternative for the first one in the chain) than an unintended tightening of scope/requirements.

**Comment by alastc** [comment]
This was approved here: https://www.w3.org/2021/11/16-ag-minutes#item13 With the caveat that the understanding doc needs additional work.

**Pull request merged**
