### PR TITLE
Merging main into working branch

### PR DESCRIPTION
**Pull request by bruce-usab**
Errors should work in both directions...

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wcag/pull/3759.html" title="Last updated on Jun 12, 2024, 1:26 PM UTC (ba81e62)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wcag/3759/80b4095...ba81e62.html" title="Last updated on Jun 12, 2024, 1:26 PM UTC (ba81e62)">Diff</a>

### CODE REVIEW

**Comment by bruce-usab** [comment]
@fstrr do [your branch](https://github.com/w3c/wcag/tree/syntax-highlighting-for-html-techniques) building locally?

If so, PRs in the other direction should get the same error messages.  On our coordination call today, Alastair suggested that as way to troubleshoot Syntax highlighting for html techniques #3381

**Comment by bruce-usab** [comment]
Welp, nevermind.  PR #3757 addresses this.

**Comment by fstrr** [comment]
Hey, @bruce-usab. This morning, I created this [Merge pr3381 and pr3738 PR](https://github.com/w3c/wcag/pull/3757) to merge the changes Patrick and I made so that, hopefully, everything is good for the broken links, syntax highlighting, etc. I just ran a local build and found an error in H91, so fixed it and pushed it up.

I'm not sure what this new PR is for though.

**Comment by patrickhlauke** [comment]
just checking, is this branch/PR needed? what is it trying to do?

**Comment by fstrr** [comment]
User blocked and reported

**Comment by bruce-usab** [comment]
Closing as OBE (and was only a test experiment regardless).

**Pull request closed without merging**
