### PR TITLE
Technique - icon contrast

### PR DESCRIPTION
**Pull request by alastc**
A new technique for non-text color contrast focused on small graphical objects, so termed 'icons'.

[Preview here](http://htmlpreview.github.io/?https://github.com/w3c/wcag/blob/tech-icon-contrast/techniques/general/icon-contrast.html).

### CODE REVIEW

**Comment by mbgower** [comment]
For the final example, I'd like a caption underneath the second image saying "Does not meet"

I think this is good information, but I'm also aware that step 5 of the procedure "is still recognizable" could lead to a lot of debate.

**Comment by detlevhfischer** [comment]
+1

**Comment by alastc** [comment]
Thanks, I've updated the last example, hopefully that is clearer @mbgower?

**Comment by allanj-uaag** [comment]
+1

**Comment by alastc** [comment]
Last example images updated, ready for publish I think @michael-n-cooper

**Comment by michael-n-cooper** [comment]
Looks ok to me at this stage of review. Needs assigning an ID and linking from Understanding.

**Comment by alastc** [comment]
Merged for publishing.

**Pull request merged**
