### PR TITLE
Fix typo in non-text-contrast.html

### LINKED ISSUE #3704: typo in Non-text contrast Understanding document
From the public comments
>Subject: Understanding and Techniques Feedback--Typo on page: Understanding Success Criterion 1.4.11
On the page [Understanding Success Criterion 1.4.11: Non-text Contrast | WAI | W3C](https://urldefense.com/v3/__https://www.w3.org/WAI/WCAG22/Understanding/non-text-contrast.html__;!!EDx7F7x-0XSOB8YS_BQ!ZJm1M7GM9lSlLE9QFcJ553p6CGFRdUH8x0Ctw4_3nduL_4GTASadPLrtorJadow_j1XSlFTLQTdd9MS-VlSeZrJjwb0$) , in the section Graphical Objects, there is a typo in the first row of the table. “Ratio” is spelled “ration”. See the attached screenshot.
 Regards,
Joseph Lakey

### PR DESCRIPTION
**Pull request by rscano**
Fixed typo

Closes #3704

### CODE REVIEW

**Review by patrickhlauke — APPROVED** [review]

**Comment by bruce-usab** [comment]
Later today, I can take a run at resolve conflicts.

**Comment by bruce-usab** [comment]
Closes #3705

**Comment by patrickhlauke** [comment]
merge conflict fixed (was just the extra space in front the self-closing xhtml-style slash on an ``)

**Comment by patrickhlauke** [comment]
actually, oops, seems resolving that merge conflict also overwrote the actual change. hang on, let me re-address this...

**Comment by bruce-usab** [comment]
Discussed on TF call 4/12 and Ready for approval.

**Pull request merged**
