### PR TITLE
Changes to 2.5.1 Pointer Gestures understanding

### PR DESCRIPTION
**Pull request by patrickhlauke**
* Add extra example that does not involve adding an actual button/control, but provides a single-pointer alternative to a multi-pointer gesture (basically what Google Maps does)
* Expand/clarify the slider/carousel example to make clear it's a flick/swipe, not a drag/swipe (which *is* permitted)
* Split the benefit to better illustrate how addressing path-based gestures, *and* multi-pointer gestures, can benefit users
* Remove the indirect benefit from adding extra buttons/controls, as the ask of the SC is not to always add extra buttons

The last two points close https://github.com/w3c/wcag/issues/747

### CODE REVIEW

**Comment by detlevhfischer** [comment]
Looks good to me!

**Comment by mbgower** [comment]
@alastc and @patrickhlauke 
Added in some slight changes in a [new commit](https://github.com/w3c/wcag/pull/1569/commits/8059364fc66340ea622861d158b909774d163071) based on today's survey and discussion, as directed.

**Comment by patrickhlauke** [comment]
@mbgower works for me

**Comment by alastc** [comment]
Approved: https://www.w3.org/2021/06/01-ag-minutes.html#t07

**Pull request merged**
