### PR TITLE
Corrections to understanding for 1.4.8 Visual Presentation

### LINKED ISSUE #2232: Understanding for 1.4.8 Visual Presentation has broken images, links
In https://w3c.github.io/wcag/understanding/visual-presentation.html in the examples, the second and third image are broken (wrong `src`).

Some of the links cited as references are now broken/obsolete as well (e.g. 465 Berea Street one)

### PR DESCRIPTION
**Pull request by patrickhlauke**
* fix broken images
* replace broken/obsolete reference links with archive.org links
* remove some of the unnecessary/inconsistent empty lines in markup
* correct `1.4.2 Resize Text` to `1.4.4 Resize Text`

Closes #2232

### CODE REVIEW

**Comment by alastc** [comment]
Merged, thank you @patrickhlauke

**Comment by patrickhlauke** [comment]
note that there seems to be some deploy issue at the moment... https://github.com/w3c/wcag/runs/5201525791

**Comment by alastc** [comment]
I think it's trying to curl some W3C scripts and failing, I don't think it's your update.

**Comment by patrickhlauke** [comment]
yeah, just flagging it (mainly because I was wondering why i wasn't seeing it updated on github.io)

**Comment by patrickhlauke** [comment]
the version here https://w3c.github.io/wcag/understanding/visual-presentation.html is still not updated. does it need to be redeployed somehow?

**Comment by patrickhlauke** [comment]
ah, but https://www.w3.org/WAI/WCAG22/Understanding/visual-presentation *is* updated. confusing

**Pull request merged**
