### PR TITLE
Removing 4.1.1

### PR DESCRIPTION
**Pull request by alastc**
Cross-reference: https://github.com/w3c/wcag/issues/2525#issuecomment-1316949146

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wcag/pull/2797.html" title="Last updated on Nov 16, 2022, 2:16 PM UTC (2b6caec)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wcag/2797/b991776...2b6caec.html" title="Last updated on Nov 16, 2022, 2:16 PM UTC (2b6caec)">Diff</a>

### CODE REVIEW

**Comment by patrickhlauke** [comment]
just noting that this may break backwards-compatibility, or rather: it's possible for a site to be conformant to 2.2 but non-conformant to 2.1/2.0.

**Comment by alastc** [comment]
Yep, and we did discuss that on the call. Partly these things should be caught by other SCs (primarily 1.3.1, 4.1.2), partly allowed by the exception "where allowed by the spec", and partly that it creates so much noise people are ignoring it anyway.

Also, a couple of people volunteered to do a mapping exercise of things 4.1.1 caught that should be caught by other SCs.

**Comment by TestPartners** [comment]
People ignoring the SC doesn't sound like a valid reason for removing it. We have rarely had a client that wasn't able to meet this SC. It's actually one of the easier SCs to fix because all you need to do is write valid code. If people are not willing to do that, it's difficult to imagine them meeting all the other success criteria.

**Comment by alastc** [comment]
> People ignoring the SC doesn't sound like a valid reason for removing it.

Unless they are ignoring it for good reason.

> We have rarely had a client that wasn't able to meet this SC. It's actually one of the easier SCs to fix because all you need to do is write valid code.

That's almost the opposite of my experience. With the exception of a publisher (who was also exporting to ePub), it is one of the most time consuming SCs to test and fix. Partly because you have to wade through so many results and filter down to what you actually need to fix. And then doing so rarely had a perceptible effect _unless_ it was also causing issues elsewhere (e.g. for 4.1.2).

I'd much rather spend time testing (or teaching people how to test) 1.3.1 and 4.1.2 efficiently. One of those methods can be validation, but the signal to noise ratio is not good in most cases I've come across.

**Comment by alastc** [comment]
Sorry, I didn't realised you'd missed all the context.

Most of it is in #2525, but see also the [original reason for the SC](https://github.com/w3c/wcag/issues/770#issuecomment-1318749819), which no longer exists.

Also, the discussion in #2525 highlighted that most people (including AG members) have been interpreting it more widely than intended, failing more things than was intended. (I.e. the 'content model' was not intended to be covered.)

Added to the fact that the "original rationale" is no longer relevant, we've had a lot of people saying that, particularly at larger scales, it creates more "busy work" than work which actually improves accessibility for people.

My personal experience has been that the useful parts are caught under 1.3.1 and 4.1.2, and the effort in 'validating' webapps based in React/Angular etc vs testing the other SCs is not worth it.

So those have been the "good reasons" for ignoring it.

**Comment by bruce-usab** [comment]
> it's possible for a site to be conformant to 2.2 but non-conformant to 2.1/2.0.

Yes, but only for a site that is non-conformant to 2.0/2.1 because of _only_ failures against SC 4.1.1 which don't map to other SC (already in 2.0/2.1) -- such as duplicated-but-unused IDs.

**Comment by patrickhlauke** [comment]
> Yes, but only for a site that is non-conformant to 2.0/2.1 because of only failures against SC 4.1.1 which don't map to other SC (already in 2.0/2.1) -- such as duplicated-but-unused IDs.

sure, but that's still breaking backwards compatibility. so IF 4.1.1 gets removed (which, don't get me wrong, I'm all in favour of), this nuance should be called out in the intro for the spec/wherever it talks about being backwards-compatible

**Comment by bruce-usab** [comment]
> this nuance should be called out in the intro for the spec/wherever it talks about being backwards-compatible

Agreed, and that was part of the conversation on the Tuesday call, but we tabled that part of the conversation.  There will be some details to work out!

**Comment by alastc** [comment]
> sure, but that's still breaking backwards compatibility.

We also need to add a little nuance, the requirement it was addressing is backwards compatible, but there can be differences in the results of an audit.

**Comment by joe-watkins** [comment]
@alastc Should this have been removed in `2.1` as well? 

https://www.w3.org/WAI/WCAG21/Understanding/parsing.html

Screenshot of 4.1.1 SC

**Comment by alastc** [comment]
Arg. Yes. It's a template thing, I'll have to check with Michael.

**Comment by joe-watkins** [comment]
@alastc Appears to be fixed! `4.1.1 Parsing` is back in WCAG 2.1 - shewey!

https://www.w3.org/WAI/WCAG21/Understanding/parsing.html

Screenshot of 4.1.1 Parsing Success Criterion page

**Pull request merged**
