### PR TITLE
Failure technique for 2.5.2

### LINKED ISSUE #372: References to a Failure for 2.5.2 Pointer Cancellation is out of date
Dear AGWG & specifically the Mobile Task Force, 

I was just looking closely at the understanding document for WCAG 2.1 SC 2.5.2 Pointer Cancellation...and I've got a question for you.

If you go to [Understanding SC 2.5.2 Pointer Cancellation](https://www.w3.org/WAI/WCAG21/Understanding/pointer-cancellation.html) and find the link text that reads 

[FM001 Failure of SC 2.5.3 due to activating a button on initial touch location rather than the final touch location](http://w3c.github.io/Mobile-A11y-TF-Note/Techniques/FM001)
And you click on that link, it goes to a page that has details about a different failure technique. The H1 of that linked page is "Content or functionality not available by touch gesture when platform assistive technology is active"

Something is out of sync.  I had a brief conversation with Jon Avila about it, and he suggested that this was an old technique that has morphed into something different, but the old wording in the Failure Technique was never updated.  He suggested I submit an issue :)

### PR DESCRIPTION
**Pull request by patrickhlauke**
Admittedly wordy (as per my usual) and a bit contrived ... take this as a first stab that can be further tweaked and optimised.

[Preview](https://raw.githack.com/w3c/wcag/patrickhlauke-issue372/techniques/failures/failure-downevent-not-upevent-no-mitigating-circumstances.html).

Closes #372

### CODE REVIEW

**Comment by patrickhlauke** [comment]
Preview version here https://raw.githack.com/w3c/wcag/7937118629653648e2ae99e5d48c787f9d87f9ee/techniques/failures/failure-downevent-not-upevent-no-mitigating-circumstances.html

**Comment by alastc** [comment]
Generally looks good, I'd like to do a quick editorial pass before putting up for the whole group, will probably go in for next weeks neeting.

**Comment by patrickhlauke** [comment]
note that for some reason the rawgithack version didn't update...here's the latest https://raw.githack.com/w3c/wcag/0df064cf7edb431010f8ef02792f218f28080e0b/techniques/failures/failure-downevent-not-upevent-no-mitigating-circumstances.html

**Comment by alastc** [comment]
If you go to the branch and view the file, use that URL for rawgit, and it will stay up to date.

**Comment by patrickhlauke** [comment]
https://raw.githack.com/w3c/wcag/patrickhlauke-issue372/techniques/failures/failure-downevent-not-upevent-no-mitigating-circumstances.html

**Comment by patrickhlauke** [comment]
@alastc @jake-abma @mbgower pushed some updates...let me know what you think, happy to tweak further.

rendered version https://raw.githack.com/w3c/wcag/patrickhlauke-issue372/techniques/failures/failure-downevent-not-upevent-no-mitigating-circumstances.html

**Comment by alastc** [comment]
Looks good, I just moved the note into the desc area (for consistency with other SCs), and prepped for publishing.

I'll leave it until tomorrow for comments, otherwise I'll merge.

**Pull request merged**
