### PR TITLE
Reword piano example

### PR DESCRIPTION
**Pull request by patrickhlauke**
Closes https://github.com/w3c/wcag/issues/771

### CODE REVIEW

**Comment by awkawk** [comment]
Patrick, do you think that this change affects the meaning, or is it just your preferred wording? My thinking is the latter, and done think that this is needed.

**Comment by patrickhlauke** [comment]
i was going by what @jake-abma suggested, but i agree with him that this is more understandable

**Comment by patrickhlauke** [comment]
to expand/clarify the reasoning:

"room for enough of the piano keys to be functionally usable"

this implies that "enough" piano keys will be functionally usable, but that there are other piano keys that aren't functionally usable ... but it's deemed that there's "enough" of them that do actually work

"the piano keys to have enough room to be functionally usable"

this on the other hand implies that *all* piano keys have enough room to be functionally usable, and there aren't piano keys that are there but NOT functionally usable

a subtle distinction, but to me (and I think @jake-abma) this makes more sense

**Comment by jake-abma** [comment]
This one is closed, but I do not see a change in Understanding docs.... do I miss something or look at the wrong place?

**Comment by patrickhlauke** [comment]
i closed it at the time because it felt like it was going nowhere...

**Comment by jake-abma** [comment]
maybe open again? you never know, it's 2021... :-)

**Comment by patrickhlauke** [comment]
can't reopen, as i deleted the original repo (was a fork on my own github account, rather than a branch here on the WCAG repo). maybe @jake-abma I can tempt you in creating a PR of your own? ;)

**Comment by jake-abma** [comment]
you're so awesome good at it, don't want to take away your compulsive hobby!

**Comment by patrickhlauke** [comment]
Superseded/picked up again over here https://github.com/w3c/wcag/pull/4528

**Pull request closed without merging**
