### PR TITLE
Adding px note to two understanding docs.

### PR DESCRIPTION
**Pull request by alastc**
Added a note about PT to PX conversion in understanding docs for 1.4.6 and 1.4.3. Also adjusted note on image of text to simplify.

### CODE REVIEW

**Comment by alastc** [comment]
I'm guessing the bibref doesn't work? Not sure how it should work though.

**Comment by patrickhlauke** [comment]
wonder if the note about CSS pt should be more explicit/walk the reader through how the value is reached (basically, this https://github.com/w3c/wcag/pull/184/commits/738095ca633e610f4424cf36a33aaea9a5677aee).

and no the bibref won't work unless you add it as well (see part of https://github.com/w3c/wcag/pull/184/commits/291f68c76771ce3de3198c759c453383360402b7)

**Comment by awkawk** [comment]
@alastc - just use a loc element with an href to the section that you want to link to.

**Comment by awkawk** [comment]
Approved by group. https://lists.w3.org/Archives/Public/w3c-wai-gl/2016AprJun/0670.html

**Pull request merged**
