### PR TITLE
Pointer cancellation jake suggestions

### LINKED ISSUE #707: 2.5.2: Pointer Cancellation mentions failure for  2.5.3, editorial issue
A failure reference for techniques mentions 2.5.3, think that needs to be 2.5.2

https://www.w3.org/WAI/WCAG21/Understanding/pointer-cancellation.html#techniques

> @@ Failure of SC 2.5.3 due to activating a button on initial touch location rather than the final touch location.

### PR DESCRIPTION
**Pull request by mbgower**
addressed editorial raised by Jake

Closes #707

### CODE REVIEW

**Comment by detlevhfischer** [comment]
+1 looks fine to me

**Comment by jake-abma** [comment]
Hi @mbgower shouldn't we need to remove the word new altogether?

**Comment by jake-abma** [comment]
see also: https://github.com/w3c/wcag/issues/708#issuecomment-488067248

**Comment by alastc** [comment]
Hi @jake-abma,

The 'new' is from the build-generator, that's in Michael's (very long) to-do list, and shouldn't affect the other aspects.

**Comment by alastc** [comment]
In fact, the technique updates were mostly already done in master, so I'm going to merge this one, it's purely editorial and will be over-ridden by whatever MichaelC does with the generator.

**Pull request merged**
