### PR TITLE
F94.xml

### PR DESCRIPTION
**Pull request by marcjohlic**
Adding a new Failure technique - F94 - per Issue #121.  
https://github.com/w3c/wcag/issues/121

### CODE REVIEW

**Comment by jnurthen** [comment]
I disagree with this failure. There are times when fields are not known to be required until the data is submitted to the server. Any failure technique must allow for this case.

I agree that if the required indicator is available visually it must also be available programatically in some way (aria-required, required or as part of the label). However, this technique only seems to allow label which is not correct.

**Comment by goetsu** [comment]
@jnurthen a note to indicate that case and an exception in the test procedure could be good for you ?
it's not my intent to allow only label as the correct solution maybe we can add correct example one using label and one using aria-describedby for example (any others ?). For sure title would be conforming but I don't think it's a good example to give

**Comment by patrickhlauke** [comment]
as noted in #121 - at least for the case of using `aria-required`, or indeed just `required` - there's quite a bit of overlap with 4.1.2

**Comment by awkawk** [comment]
Closing without consensus.

**Pull request closed without merging**
