### PR TITLE
minor punctuation fixes - adding missing commas

### PR DESCRIPTION
**Pull request by shawna-slh**
from @pallabiwrites   https://github.com/w3c/wai-intro-wcag/pull/307/files

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wcag/pull/4025.html" title="Last updated on Aug 23, 2024, 9:29 AM UTC (e701afa)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wcag/4025/94c76c8...e701afa.html" title="Last updated on Aug 23, 2024, 9:29 AM UTC (e701afa)">Diff</a>

### CODE REVIEW

**Comment by shawna-slh** [comment]
i.e. -> i.e.,

comma also needed in Notes in Success Criterion 2.5.1 Pointer Gestures and 2.5.2 Pointer Cancellation

**Review by patrickhlauke — APPROVED** [review]

**Comment by shawna-slh** [comment]
@patrickhlauke did you also take care of
> i.e. -> i.e.,
> comma also needed in Notes in Success Criterion 2.5.1 Pointer Gestures and 2.5.2 Pointer Cancellation

?

**Comment by patrickhlauke** [comment]
i only approved the PR, not work on anything further no

**Comment by patrickhlauke** [comment]
done a few more stragglers. note that there's the same kind of issue with `e.g.`, much more pervasive throughout a LOT of documents. though it may actually be a good idea to take a step back and see if we want to use something nicer, like "for instance" / "for examples" instead, to aid comprehension. but leaving that as an exercise for another day...

**Pull request merged**
