### PR TITLE
Issue 3138 numbering

### LINKED ISSUE #3138: Examples are mis-numbered
In the spec, the examples are numbered across section. 5.2.3 has the first example ("example 1") and the glossary item for Abbreviation has examples 2-4. This continues until the glossary item for "web content" has examples 38-42.

It seems that the ideal situation is:

- Items with individual examples would have "Example"
- items with multiple examples would have "Example 1", "Example 2", etc
- The same logic should apply to Notes. We lost numbering for multiple notes when we did WCAG 2.1

### PR DESCRIPTION
**Pull request by michael-n-cooper**
fixes #3138 

Note this changes the text of note and example headings, but they continue to have respec-generated ids which won't "match up", assuming that's minor.

### CODE REVIEW

**Comment by michael-n-cooper** [comment]
[Preview](https://raw.githack.com/w3c/wcag/issue-3138-numbering/guidelines/index.html)

**Review by alastc — APPROVED** [review]
It seems to work, I didn't realise it would be done in JS, but I guess that's easier than with XSL!

**Comment by awkawk** [comment]
Great, thanks.

**Comment by alastc** [comment]
Would this also need merging into WCAG 2.1 for republishing?

**Pull request merged**
