### PR TITLE
Update content-on-hover-or-focus.html

### PR DESCRIPTION
**Pull request by mbgower**
As per the discussion in https://github.com/w3c/wcag/issues/582, this erratum is intended to address potential misreading of the normative text for 1.4.13 Content on Hover or Focus in the final Persistent bullet. The key objective was to replace the word "trigger" so that users would not interpret that the trigger itself must be removed to meet the criterion.

The revised version reads:
> The additional content remains visible until the user dismisses it, its information is no longer valid, or the hover or focus is removed.

### CODE REVIEW

**Comment by awkawk** [comment]
Why change the order? Can we just remove "trigger" so the change is as minimal as possible?

**Comment by mbgower** [comment]
As per comments, I can live with that, but it _does_ read somewhat awkwardly, in terms of what "it" refers to.
> The additional content remains visible until the hover or focus is removed, the user dismisses it, or its information is no longer valid.

If you think it will be easier to pass as an erratum, I can live with it and I do not anticipate objections from those involved in the discussion (which is summarized [here](https://github.com/w3c/wcag/issues/582#issuecomment-457234323).

As Steve mentions, I also think this could be clarified in the Understanding document without issuing an erratum, should that prove the path of least resistance.

**Comment by mbgower** [comment]
PS normally when I create a local branch, my client offers me a chance to push it. I didn't get it this time. Not sure if that is due to permissions? but I assume that is what is causing the "This branch has not been deployed" message

**Comment by alastc** [comment]
Don't worry about the deployment messages, there's some build-test type stuff happening but it seems a bit flakey, the errors are generally due to time-outs. That it is showing the 'merge pull request' (to me at least) is a good sign.

**Comment by mbgower** [comment]
As per https://github.com/w3c/wcag/issues/582#issuecomment-462393140, I am recommending this PR be withdrawn and, with @detlevhfischer's agreement, the original issue be closed.

**Comment by alastc** [comment]
Reviewing potential errata, given there are voices that would insist on it being an errata for 2.1, I'll close as requested.

**Pull request closed without merging**
