### PR TITLE
Tech timeout 20 hours or greater

### PR DESCRIPTION
**Pull request by patrickhlauke**
This branch never had a pull request made. Suggest we either take/consider this, or delete both this PR and branch.

### CODE REVIEW

**Comment by bruce-usab** [comment]
Discussed on TF call 9/13.  This would be new technique from a stale branch. TBD.

**Comment by bruce-usab** [comment]
@goodwitch are you still of the opinion that this is an important gap to fill?  That is, do we need a technique for testing that a timeout does not occur within 20 hours?  And if so, is [what @patrickhlauke has drafted](./4058/files) sufficient?  Thank you.

**Comment by patrickhlauke** [comment]
> And if so, is [what @patrickhlauke has drafted](https://github.com/w3c/wcag/pull/4058/files) sufficient?

yo clarify, this is literally just taking the branch that @goodwitch opened at the time and turning it into a PR. it will need massaging to be mergeable

**Comment by bruce-usab** [comment]
On TF call 10/4, @alastc offered to ask @goodwitch offline about the need for this PR.

**Comment by patrickhlauke** [comment]
I would suggest closing this (and deleting the branch), as we likely don't need a technique that literally says "to test there's a 20 hour timeout, set yourself a timer for 19 hours 59 minutes and check if anything happens in that last minute..."

**Pull request closed without merging**
