### PR TITLE
mark up changes of language in 3.1.2 Understanding document

### LINKED ISSUE #2497: WCAG 2.1 Language Of Parts Understanding document doesn't mark up changes of language
Most changes of language are marked up in the 2.0 equivalent.

### PR DESCRIPTION
**Pull request by fstrr**
Marked up changes of language.

Also:
1. Updated Resources links to add a link to the current HTML spec and update W3C document titles.
2. Added a link to the existing text telling the user to reference that document.

Closes #2497

### CODE REVIEW

**Comment by detlevhfischer** [comment]
@fstrr The only change I would suggest is to the example of Castellano with `lang="es"` - would it not be better to replace this with `<span lang="ca">Catalan</span>` to cover sub-national languages? I guess people might be confused by "Castellano" (instead of "Spanish").

**Comment by fstrr** [comment]
@detlevhfischer Done!

**Comment by detlevhfischer** [comment]
@fstrr Another thought: Wouldn't it be `<span lang="nl">Dutch</span>` rather than `<span lang="nl">Netherlands</span>`? (@jake-abma would know)

**Comment by fstrr** [comment]
or @WilcoFiers

**Comment by fstrr** [comment]
You made me double-check that it's <span lang="nl">Nederlands</span> (correct, and in the Understanding document and still in my PR) and not <span lang="nl">Netherlands</span> (not correct, in your comment above)! I had a look online and apparently there isn't a word "Dutch" in Dutch—it's apparently Nederlands.

**Pull request merged**
