### PR TITLE
Adding PX comment to G18 and G145.

### PR DESCRIPTION
**Pull request by alastc**
Same paragraph added to the understanding documents in a note element (hope that's valid for techniques?).

### CODE REVIEW

**Comment by awkawk** [comment]
@alastc - can you make the bibref element into the loc like in pull 188?

**Comment by alastc** [comment]
Ach, copy paste error. Sorry, will do.

**Comment by awkawk** [comment]
AWK reminding himself that the group wanted the first sentence to read: "The size in points should be obtained from the user agent, or calculated based on font metrics as the user agent does, when evaluating this success criterion."

**Comment by awkawk** [comment]
CfC accepted June 14. Merged

**Pull request merged**
