### PR TITLE
Tech hover focus hoverable

### PR DESCRIPTION
**Pull request by detlevhfischer**
A [rendered version](https://raw.githack.com/w3c/wcag/tech-hover-focus-hoverable/techniques/client-side-script/tech-hover-focus-hoverable.html).

### CODE REVIEW

**Comment by detlevhfischer** [comment]
This was the example provided by @mraccess77 in the original issue (now closed) https://github.com/w3c/wcag/issues/529 :

> I made an example of the technique here https://labs.levelaccess.com/index.php/Additional_Content_on_Hover_or_Focus

Just putting it here for reference. There were also responses in that issue as to its suitability and likely changes needed.

**Comment by alastc** [comment]
+1

**Comment by jake-abma** [comment]
+1

Small text fixes:

1. dissmissible  => dismissible

2.
> focus the trigger with the keyboard 

can we delete "with the keyboard" here, or add other methods here as the keyboard is not the only method to put focus on a element.

**Comment by detlevhfischer** [comment]
@mraccess77 ,
Many thanks for improving the code - but I think the example still needs more work (I felt from the start that it was not easy-peasy).
The problem is if you focus the trigger with the keyboard and then use the mouse to move the cursor over the popup, the popup closes. So the two input modalities are not in sync.
Detlev

**Comment by detlevhfischer** [comment]
@mraccess77  I guess strictly speaking your code example is fine since the SC does not require that content on (keyboard) focus is hoverable. However, arguably it would be nice if it the additional content brought up by keyboard focus would remain visible for pointer exploration (see the issue I have raised today: https://github.com/w3c/wcag/issues/582 ).

**Pull request merged**
