### PR TITLE
Add F42 as failure for 4.1.2

### PR DESCRIPTION
**Pull request by patrickhlauke**
Closes https://github.com/w3c/wcag/issues/1263

(also cleans up the markup of 4.1.2 understanding, removing all unnecessary/excessive line breaks, fixes the invalid use of `</meta>`, and removes the unnecessary techniques link text which is autopopulated at publish time)

### CODE REVIEW

**Comment by patrickhlauke** [comment]
See deploy previews https://deploy-preview-4052--wcag2.netlify.app/techniques/failures/f42 and https://deploy-preview-4052--wcag2.netlify.app/techniques/failures/f42

**Comment by detlevhfischer** [comment]
At to [F42](https://deploy-preview-4052--wcag2.netlify.app/techniques/failures/f42#example-4-scripting-a-div-element), section "Example 4: Scripting a div element": the code example at the end has no `tabindex="0"` but the example intro claims the author has made the pseudo-link keyboard-accessible.
Should this technique have a note that if pseudo-links that are fully keyboard accessible **and** carry a role="link", they would not fail?

I can create a PR to implement that if people think it would be worthwhile doing.

**Comment by patrickhlauke** [comment]
> At to [F42](https://deploy-preview-4052--wcag2.netlify.app/techniques/failures/f42#example-4-scripting-a-div-element), section "Example 4: Scripting a div element": the code example at the end has no tabindex="0" but the example intro claims the author has made the pseudo-link keyboard-accessible.

urgh, good catch. suggest making a small PR for that fix

> Should this technique have a note that if pseudo-links that are fully keyboard accessible and carry a role="link", they would not fail?

the technique already has the note about "It is possible to use the ARIA role attribute to identify an anonymous element as link control for assistive technologies …". the "fully keyboard accessible" part would be relevant for the 2.1.1 aspect, yes. Suggest amending/expanding that note to clarify that part yes (can be in the same PR as the above)

**Review by kfranqueiro — APPROVED** [review]
I diffed builds before/after the changes in this PR to confirm that nothing unexpected happened due to the formatting cleanup.

**Pull request merged**
