### PR TITLE
Fix typo in Understanding 2.5.3: Label in Name

### PR DESCRIPTION
**Pull request by 36degrees**

### CODE REVIEW

**Comment by 36degrees** [comment]
Anyone able to approve this hopefully non-controversial, single character change that fixes a typo? 🙂

**Comment by patrickhlauke** [comment]
@36degrees looking at the fact that currently there's 160 open PRs here, just a warning that PRs can take "a while" to be approved and merged, even when they're small and non-controversial... /cc @alastc

**Comment by 36degrees** [comment]
@patrickhlauke apologies – I did check the list of open PRs after writing my comment and when I realised there were quite a few similar PRs that had been open longer, I deleted my comment. Definitely don't want to add pressure, I was just reviewing what PRs I had open and thought this might have been missed.

Happy for this to just sit here, unless there's anything I can do to help.

(For transparency, and to put Patrick's reponse in context, my now-deleted comment said something along the lines of 'Is anyone able to review this one character, hopefully non-controversial change?')

**Comment by patrickhlauke** [comment]
no worries, was just managing your expectations :)

**Comment by alastc** [comment]
Typos I'm happy to merge, it's when things need approval that it goes into a long queue.

**Pull request merged**
