### PR TITLE
Create shortcut-mechanism.html

### PR DESCRIPTION
**Pull request by mbgower**
First draft of sufficient technique.

[Preview](https://raw.githack.com/w3c/wcag/keyboardShortcutSufficientTechnique/techniques/general/shortcut-mechanism.html).

### CODE REVIEW

**Comment by detlevhfischer** [comment]
Here is a rendered view:
https://raw.githack.com/w3c/wcag/baa2cd3a31f7c6187335bcda27e4fe334d9625e3/techniques/general/shortcut-mechanism.html

**Comment by patrickhlauke** [comment]
does the test procedure need an initial step to first determine if the page/site actually uses any character key shortcuts in the first place, and maybe even a follow-up step to check if they're single character ones?

and if so, could it then also benefit from a note about being able to at least narrow this down by checking JS for presence of `keydown`/`keyup`/`keypress` listeners? (similar to the note i added to the 2.5.2 failure technique https://github.com/w3c/wcag/pull/815 )

**Comment by detlevhfischer** [comment]
@patrickhlauke   This bookmarklet takes another route, checks if anything happens when character keys are pressed (by script)  - but it may have flaws:
http://3needs.org/en/testing/code/kb-shortcuts.html - comment if you like in issue #833

**Comment by mbgower** [comment]
@patrickhlauke [asked](https://github.com/w3c/wcag/pull/836#issuecomment-515446079):
> does the test procedure need an initial step to first determine if the page/site actually uses any character key shortcuts in the first place, and maybe even a follow-up step to check if they're single character ones?

My feeling would be it doesn't. There are sufficient technique procedures where the assumption is that the user is aware of what they're doing.  For instance  [G14: Ensuring that information conveyed by color differences is also available in text](https://www.w3.org/WAI/WCAG21/Techniques/general/G14) has a procedure that begins:
> For each item where a color difference is used to convey information:

That seems pretty similar to 'For each character key shortcut..." I don't feel like a success criterion needs to be iron-clad in the same way as a failure. Here the user is just trying to know how they confirm they've properly handled their shortcuts.  I'm not going to die on this hill, but more verbage seems unnecessary to me.

> and if so, could it then also benefit from a note about being able to at least narrow this down by checking JS for presence of keydown/keyup/keypress listeners?

Remember, this isn't a test to locate shortcuts. It's a technique to be able to turn them off. We've got content somewhat similiar to what you mention in the failure technique, which is I think where it makes more sense. I'll also mention that feedback I had from some rules writers was that trying to work off those keydown/up/press events to find character key shortcuts would lead to flagging many 'false' PVs.

**Comment by mraccess77** [comment]
While this is a technique about turning them off (or changing so they are not single key)-- sending keys might be the only way to know a shortcut exists.   In my opinion the first step would be to check the documentation for single key short cuts, then check settings to see if they can be turned off or changed.  Third would to be verify that actually works and fourth to test for undocumented shortcuts.

**Comment by mbgower** [comment]
If we are going to go to this level in the procedure, I think we're going to have to add in additional information in the body of the technique. So I will add a section that talks about how to determine shortcuts.
I continue to feel like folks are asking for more information here than is in a lot of existing techniques. I'll review a bunch and see if I can find a sweet spot.

**Comment by mbgower** [comment]
Many of the script techniques (which have many parallels to this) have either a similar set up to what I've proposed (e.g., "For pages that dynamically create new content") or pretty broad set ups (e.g., "Find all interactive functionality")
- https://www.w3.org/WAI/WCAG21/Techniques/client-side-script/SCR1
- https://www.w3.org/WAI/WCAG21/Techniques/client-side-script/SCR2 (which is a much broader case, with very little verbage around the establishing scenario)
- https://www.w3.org/WAI/WCAG21/Techniques/client-side-script/SCR16
- https://www.w3.org/WAI/WCAG21/Techniques/client-side-script/SCR18
- https://www.w3.org/WAI/WCAG21/Techniques/client-side-script/SCR20
- https://www.w3.org/WAI/WCAG21/Techniques/client-side-script/SCR21

I'm not saying there aren't more stringent ones, but...

**Comment by mbgower** [comment]
I've pushed some changes to address these comments.

**Comment by alastc** [comment]
Accepted in the call, just needs prepping for publication (changing filename, updating understanding doc).

**Pull request merged**
