### PR TITLE
fix: update reflow.html to have responsive video

### PR DESCRIPTION
**Pull request by davatron5000**
👋  In a somewhat unexpected twist, the page for understanding the WCAG rule about not having two-dimensional scrollbars had two-dimensional scrollbars due to an overflowing video. This fix addresses that.

- [x] Add `height`/`width` to `<video>` to establish `aspect-ratio`
- [x] ~Add `style="max-width: 100%; height: auto"` to allow video to squish and maintain aspect ratio.~

The inline `style` attribute is regrettable but there were no instructions on how to build the project locally so I couldn't pinpoint how `style.css` was being generated or included.

Closes https://github.com/w3c/wcag/issues/3401

### CODE REVIEW

**Comment by patrickhlauke** [comment]
see also https://github.com/w3c/wcag/issues/3401

I suggest this should actually be fixed at source/in the main stylesheet, not on an ad-hoc basis

**Review by patrickhlauke — CHANGES_REQUESTED** [review]
Suggest this change is made in the general stylesheet used for understanding docs instead

**Comment by davatron5000** [comment]
Ok. Just so I'm clear, I should fork the the `wai-website-theme` repo and PR a fix for video styles there? Is that what you mean by "general stylesheet"?

https://github.com/w3c/wai-website-theme/blob/master/_components/images.css#L20

I can update this PR to only add the height/width which will help with the overall CLS.

**Comment by davatron5000** [comment]
Upstream PR created https://github.com/w3c/wai-website-theme/pull/58

**Comment by patrickhlauke** [comment]
thanks @davatron5000 ... I'll leave @alastc @iadawn to comment here on whether or not this upstream PR is all that's needed (as I'm not sure if it's different teams/people responsible for these things)

**Comment by patrickhlauke** [comment]
As this dropped off the radar, added to the WCAG 2.x backlog

**Comment by alastc** [comment]
There's no change included in the PR, do we need to update the CSS for the repo?

**Comment by fstrr** [comment]
@alastc There's an upstream [PR for this on the WAI website theme repo.](https://github.com/w3c/wai-website-theme/pull/58), which was approved last year. I've emailed @iadawn to see if we can get this live.

**Comment by patrickhlauke** [comment]
Closing this as it was fixed

**Pull request closed without merging**
