### PR TITLE
Tweak 3.3.2 understanding benefits to align with intent

### LINKED ISSUE #1793: add text "or instructions" in Intent for 3.3.2: Labels or Instructions
https://www.w3.org/WAI/WCAG22/Understanding/labels-or-instructions.html

Last sentence of Intent is:

> While this Success Criterion requires that controls and inputs have labels, whether or not these labels are sufficiently clear or descriptive is covered separately by 2.4.6: Headings and Labels.

The requirement is "Labels OR instructions" so I think the text must be:

> While this Success Criterion requires that controls and inputs have labels **or instructions**, whether or not these labels are sufficiently clear or descriptive is covered separately by 2.4.6: Headings and Labels.

The last part of the sentence doesn't fit anymore now because of the "instructions" part.

I think the text about "sufficiently clear or descriptive" is true for the Labels, not sure if that is also true for the instructions...

As in: "whether or not these labels OR INSTRUCTIONS are sufficiently clear or descriptive is covered separately by 2.4.6: Headings and Labels" is not a match.

So do the instructions need to be "clear or descriptive"? Guess so, also for this SC, BUT again, mixing two things in one SC but having different conditions make it harder to digest.

A clear writing on the difference would be appreciated as it causes confusion.

### LINKED ISSUE #1794: Examples not correct for 3.3.2: Labels or Instructions
https://www.w3.org/WAI/WCAG22/Understanding/labels-or-instructions.html

The following **Examples** are not for this SC as they are about clear and descriptive, not that there is a label present weather or not it makes sense:

> - A field for entering a given name is clearly labeled with "Given Name" and the field for family name is labeled "Family Name" to avoid confusion over which name is requested.
> - A U.S. phone number separates the area code, exchange, and number into three fields. Parentheses surround the area code field, and a dash separates the exchange and number fields. While the punctuation provides visual clues to those familiar with the U.S. telephone number format, the punctuation is not sufficient to label the fields. The single "Phone number" label also cannot label all three fields. To address this, the three fields are grouped in a fieldset with the legend "Phone number". Visual labels for the fields (beyond the punctuation) cannot be provided in the design, so invisible labels are provided with the "title" attribute to each of the three fields. The value of this attribute for the three fields are, respectively, "Area Code", "Exchange", and "Number".

The problem with the examples is of course that they do not have to be "sufficiently clear or descriptive" but that they might also serve as a instruction, thus pushing them in a truly grey area weather it is 3.3.2 OR 2.4.6...

The blur for clear / descriptive and just being present needs to be shown as it will otherwise confuse what is needed exactly.

Based on:

> While this Success Criterion requires that controls and inputs have labels, whether or not these labels are sufficiently clear or descriptive is covered separately by 2.4.6: Headings and Labels.

### PR DESCRIPTION
**Pull request by patrickhlauke**
Closes https://github.com/w3c/wcag/issues/1791, closes #1793, closes #1794

The main thrust of these changes are to remove any impression that the Labels or Instructions SC covers the _quality_ of a label or instruction. The SC is merely about them _existing_. (Heading and Labels is the SC that covers _how_ the label is described).

### CODE REVIEW

**Comment by patrickhlauke** [comment]
While this is quite minimal...any chance to get this looked at/voted on/merged? @alastc

**Review by mbgower — APPROVED** [review]

**Comment by mbgower** [comment]
One thought I had about this. If inputs are marked as required (or not), I think a legend could qualify as an "instruction". This consideration seems _almost_ orthogonal to this SC -- and I think may be covered in another open issue -- but I wanted to flag this as an area still needing some attention and discussion.

**Comment by mraccess77** [comment]
I agree with Mike that 3.3.2 covers instructions as well that may not be labels under SC 2.4.6

**Comment by patrickhlauke** [comment]
@mbgower how do you see that affecting this PR?

**Comment by mbgower** [comment]
> @mbgower how do you see that affecting this PR?

I think the PR represents an improvement on guidance overall. But I think we should discuss form legends (particularly on required or optional fields)  in light of this discussion at our Friday call. For example, the [guidance we've employed at IBM](https://www.ibm.com/able/toolkit/design/visual/#required-fields) is that where there is use of a symbol, or where only some fields are marked, either as required or optional, there should be some instruction/legend. I'm not suggesting IBM's prescriptive guidance should be adopted by the WG; simply that IBM felt supported in making that guidance based on the wording of the relevant SC.s

**Review by bruce-usab — APPROVED** [review]
I am not certain that an asterisk is universally recognized as meaning required (and so no further explanation needed), but I concur with proposed changes.

**Comment by mbgower** [comment]
Opened https://github.com/w3c/wcag/discussions/3622

**Pull request merged**
