### PR TITLE
Fix link text in understanding 1.2.3

### LINKED ISSUE #3639: Incorrect links
Refers to [Understanding SC 1.2.3](https://www.w3.org/WAI/WCAG22/Understanding/audio-description-or-media-alternative-prerecorded)

There are incorrect text links (KS numbers) in the following excerpt:

>> See also [1.2.2: Audio Description (Prerecorded)](https://www.w3.org/WAI/WCAG22/Understanding/audio-description-prerecorded), [1.2.2: Extended Audio Description (Prerecorded)](https://www.w3.org/WAI/WCAG22/Understanding/extended-audio-description-prerecorded) and [1.2.3: Media Alternative (Prerecorded)](https://www.w3.org/WAI/WCAG22/Understanding/media-alternative-prerecorded).

It should be:
See also [**1.2.5**: Audio Description (Prerecorded)](https://www.w3.org/WAI/WCAG22/Understanding/audio-description-prerecorded), [**1.2.7**: Extended Audio Description (Prerecorded)](https://www.w3.org/WAI/WCAG22/Understanding/extended-audio-description-prerecorded) and [**1.2.8**: Media Alternative (Prerecorded)](https://www.w3.org/WAI/WCAG22/Understanding/media-alternative-prerecorded).

### PR DESCRIPTION
**Pull request by patrickhlauke**
Closes #3639

### CODE REVIEW

**Review by alastc — APPROVED** [review]

**Comment by bruce-usab** [comment]
Discussed on 1/19, facilitators need to get more clarity on syntax and build issues.

**Comment by patrickhlauke** [comment]
@bruce-usab i don't think this one needed clarity relating to build issue, as the links themselves work currently, and this just changes the link text which won't affect their working/not working

**Comment by bruce-usab** [comment]
Thanks @patrickhlauke , clearly, my note taking stands to be improved...

**Comment by patrickhlauke** [comment]
@bruce-usab nah, all good, we did probably have three concurrent discussions at the time ;)

**Pull request merged**
