### PR TITLE
Technique and example for reducing motion sc.2.3.3

### PR DESCRIPTION
**Pull request by anevins12**
Demonstration of the 'animation-from-interactions' [SC.2.3.3](https://www.w3.org/WAI/WCAG21/Understanding/animation-from-interactions.html).

[Rendered Preview](https://cdn.staticaly.com/gh/w3c/wcag/tech-reduce-motion/techniques/css/reduce-motion-query.html).

### CODE REVIEW

**Comment by alastc** [comment]
Updated based on the [previous call](https://www.w3.org/2018/12/18-ag-minutes.html#item05):

- Moved the resources from the technique to the understanding doc.
- Updated the example to trigger movement instead of a colour inversion.

Ready for re-review & hopefully approval now.

**Comment by jake-abma** [comment]
Hi @alastc  , seems like the page isn't working properly, couldn't check... Please check

**Comment by nschonni** [comment]
Looks like the preview is using a retired Yahoo API https://github.com/htmlpreview/htmlpreview.github.com/issues/66

**Comment by alastc** [comment]
@jake-abma, @nschonni thanks, I've updated the link to use statically.com

**Pull request merged**
